pub mod cli;
pub mod config;
pub mod diff;
pub mod languages;
pub mod mapper;
pub mod mutator;
pub mod operators;
pub mod parser;
pub mod report;
pub mod runner;

use std::fmt;
use std::path::PathBuf;
use std::time::Duration;

/// A file with changed line ranges from a diff
#[derive(Debug, Clone)]
pub struct ChangedFile {
    pub path: PathBuf,
    pub hunks: Vec<LineRange>,
}

/// A range of changed lines (1-indexed, inclusive)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LineRange {
    pub start: usize,
    pub end: usize,
}

/// A concrete mutation to apply to source code
#[derive(Debug, Clone)]
pub struct Mutation {
    pub id: u32,
    pub file: PathBuf,
    pub line: usize,
    pub column: usize,
    pub operator: String,
    pub description: String,
    pub original: String,
    pub replacement: String,
    pub byte_range: std::ops::Range<usize>,
}

/// Candidate mutation generated by an operator before execution
#[derive(Debug, Clone)]
pub struct MutationCandidate {
    pub byte_range: std::ops::Range<usize>,
    pub replacement: String,
    pub operator_id: String,
    pub description: String,
}

/// Result of running a single mutation
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MutationResult {
    Killed,
    Survived,
    Timeout,
    BuildError,
}

impl fmt::Display for MutationResult {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            MutationResult::Killed => write!(f, "killed"),
            MutationResult::Survived => write!(f, "survived"),
            MutationResult::Timeout => write!(f, "timeout"),
            MutationResult::BuildError => write!(f, "build error"),
        }
    }
}

/// Aggregated results from a mutation testing run
#[derive(Debug)]
pub struct MutationReport {
    pub results: Vec<(Mutation, MutationResult)>,
    pub duration: Duration,
    pub total: usize,
    pub killed: usize,
    pub survived: usize,
    pub timeout: usize,
    pub build_errors: usize,
}
