pub mod baseline;
pub mod build_check;
pub mod cache;
pub mod cli;
pub mod config;
pub mod coverage;
pub mod diff;
pub mod languages;
pub mod lock;
pub mod mapper;
pub mod mutator;
pub mod operators;
pub mod parser;
pub mod report;
pub mod runner;

#[cfg(test)]
pub mod test_helpers;

use std::fmt;
use std::path::PathBuf;
use std::time::Duration;

/// Convert a 0-indexed tree-sitter row to a 1-indexed source line number.
///
/// Unified diffs and user-facing output use 1-indexed lines; tree-sitter uses
/// 0-indexed rows. This function is the single conversion point between the two
/// systems, preventing scattered `+ 1` arithmetic and off-by-one bugs.
#[inline]
pub fn ts_row_to_line(row: usize) -> usize {
    row + 1
}

/// A file with changed line ranges from a diff
#[derive(Debug, Clone)]
pub struct ChangedFile {
    pub path: PathBuf,
    pub hunks: Vec<LineRange>,
}

/// A range of changed lines (1-indexed, inclusive).
///
/// All line numbers in togi are 1-indexed to match unified diff format and
/// user-facing output. Tree-sitter 0-indexed rows must be converted via
/// [`ts_row_to_line`] before comparison with these ranges.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LineRange {
    pub start: usize,
    pub end: usize,
}

/// A concrete mutation to apply to source code
#[derive(Debug, Clone)]
pub struct Mutation {
    pub id: u32,
    pub file: PathBuf,
    pub language: String,
    pub line: usize,
    pub column: usize,
    pub operator: String,
    pub description: String,
    pub original: String,
    pub replacement: String,
    pub byte_range: std::ops::Range<usize>,
}

/// Candidate mutation generated by an operator before execution
#[derive(Debug, Clone)]
pub struct MutationCandidate {
    pub byte_range: std::ops::Range<usize>,
    pub replacement: String,
    pub operator_id: String,
    pub description: String,
}

/// Result of running a single mutation
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MutationResult {
    Killed,
    Survived,
    Timeout,
    BuildError,
}

impl fmt::Display for MutationResult {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            MutationResult::Killed => write!(f, "killed"),
            MutationResult::Survived => write!(f, "survived"),
            MutationResult::Timeout => write!(f, "timeout"),
            MutationResult::BuildError => write!(f, "build error"),
        }
    }
}

/// Aggregated results from a mutation testing run
#[derive(Debug)]
pub struct MutationReport {
    pub results: Vec<(Mutation, MutationResult)>,
    pub duration: Duration,
    pub total: usize,
    pub killed: usize,
    pub survived: usize,
    pub timeout: usize,
    pub build_errors: usize,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ts_row_to_line_converts_zero_indexed() {
        assert_eq!(ts_row_to_line(0), 1);
        assert_eq!(ts_row_to_line(9), 10);
        assert_eq!(ts_row_to_line(99), 100);
    }

    #[test]
    fn mutation_result_display() {
        assert_eq!(MutationResult::Killed.to_string(), "killed");
        assert_eq!(MutationResult::Survived.to_string(), "survived");
        assert_eq!(MutationResult::Timeout.to_string(), "timeout");
        assert_eq!(MutationResult::BuildError.to_string(), "build error");
    }

    #[test]
    fn line_range_construction() {
        let r = LineRange { start: 5, end: 10 };
        assert_eq!(r.start, 5);
        assert_eq!(r.end, 10);
    }

    #[test]
    fn line_range_equality() {
        let a = LineRange { start: 1, end: 3 };
        let b = LineRange { start: 1, end: 3 };
        let c = LineRange { start: 1, end: 4 };
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    #[test]
    fn changed_file_construction() {
        let cf = ChangedFile {
            path: PathBuf::from("src/main.go"),
            hunks: vec![
                LineRange { start: 1, end: 5 },
                LineRange { start: 10, end: 15 },
            ],
        };
        assert_eq!(cf.path, PathBuf::from("src/main.go"));
        assert_eq!(cf.hunks.len(), 2);
    }

    #[test]
    fn mutation_construction() {
        let m = Mutation {
            id: 0,
            file: PathBuf::from("test.go"),
            language: "go".into(),
            line: 5,
            column: 3,
            operator: "lt_to_lte".into(),
            description: "replace < with <=".into(),
            original: "<".into(),
            replacement: "<=".into(),
            byte_range: 10..11,
        };
        assert_eq!(m.id, 0);
        assert_eq!(m.line, 5);
        assert_eq!(m.original, "<");
        assert_eq!(m.replacement, "<=");
    }
}
